# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'CDDStoreDemo' do

pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'Masonry'
pod 'SDCycleScrollView'
pod 'FMDB','~> 2.2'
pod 'ZYCornerRadius'
pod 'SDWebImage' ,"3.8.2"
pod 'ZXingObjC'
pod 'TZImagePickerController',"1.7.0"
pod 'IQKeyboardManager' ,"3.3.0"
pod 'AFNetworking', '3.1.0'

pod 'UMengUShare/UI'

# 集成微信(精简版0.2M)
pod 'UMengUShare/Social/ReducedWeChat'

# 集成微信(完整版14.4M)
pod 'UMengUShare/Social/WeChat'

# 集成QQ/QZone/TIM(精简版0.5M)
pod 'UMengUShare/Social/ReducedQQ'

# 集成QQ/QZone/TIM(完整版7.6M)
pod 'UMengUShare/Social/QQ'

# 集成新浪微博(精简版1M)
pod 'UMengUShare/Social/ReducedSina'

pod 'BlocksKit', '2.2.5'
pod 'libextobjc', '0.4.1'
pod 'MBProgressHUD', '0.9.2'



end
